# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e675243ba734486e657d05b22ed5e55c638aa6137a7981888b720b3dd5a20dfa81014b22202bb79a5de3df7a5fcc03e0e05e222b907795456b2abd029c4e6cf

test:
  secret_key_base: 78f6c4bf046b9f84b09e2e1d7995ac7aada4390c0f6ef3e5e99a8358ee181cff88782881728144dfe37666bd0ea0283b21537d1340d115442add1ec78095da65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
